// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GatewayAuthServiceClient is the client API for GatewayAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayAuthServiceClient interface {
	// Authorize authorization request with request headers and url.
	Authorize(ctx context.Context, in *AuthorizeRequest, opts ...grpc.CallOption) (*AuthorizeResponse, error)
}

type gatewayAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayAuthServiceClient(cc grpc.ClientConnInterface) GatewayAuthServiceClient {
	return &gatewayAuthServiceClient{cc}
}

func (c *gatewayAuthServiceClient) Authorize(ctx context.Context, in *AuthorizeRequest, opts ...grpc.CallOption) (*AuthorizeResponse, error) {
	out := new(AuthorizeResponse)
	err := c.cc.Invoke(ctx, "/GatewayAuthService/Authorize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayAuthServiceServer is the server API for GatewayAuthService service.
// All implementations must embed UnimplementedGatewayAuthServiceServer
// for forward compatibility
type GatewayAuthServiceServer interface {
	// Authorize authorization request with request headers and url.
	Authorize(context.Context, *AuthorizeRequest) (*AuthorizeResponse, error)
	mustEmbedUnimplementedGatewayAuthServiceServer()
}

// UnimplementedGatewayAuthServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGatewayAuthServiceServer struct {
}

func (UnimplementedGatewayAuthServiceServer) Authorize(context.Context, *AuthorizeRequest) (*AuthorizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authorize not implemented")
}
func (UnimplementedGatewayAuthServiceServer) mustEmbedUnimplementedGatewayAuthServiceServer() {}

// UnsafeGatewayAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayAuthServiceServer will
// result in compilation errors.
type UnsafeGatewayAuthServiceServer interface {
	mustEmbedUnimplementedGatewayAuthServiceServer()
}

func RegisterGatewayAuthServiceServer(s grpc.ServiceRegistrar, srv GatewayAuthServiceServer) {
	s.RegisterService(&GatewayAuthService_ServiceDesc, srv)
}

func _GatewayAuthService_Authorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayAuthServiceServer).Authorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GatewayAuthService/Authorize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayAuthServiceServer).Authorize(ctx, req.(*AuthorizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayAuthService_ServiceDesc is the grpc.ServiceDesc for GatewayAuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayAuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GatewayAuthService",
	HandlerType: (*GatewayAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authorize",
			Handler:    _GatewayAuthService_Authorize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway-auth.proto",
}
